### ISSUE TITLE
Payment declined not returning type "Unknown"

### ISSUE THREAD

**Issue by pcobas** [paypal/here-sideloader-api-samples#18]
Sometimes the Paypal Here app  declines a payment and does not return the Type as Unknown, as it does most of the times

An example of this can be seen in  the following response (a declined payment in the Paypal Here app): 
"Type=CHIP&InvoiceId=INV2-B8C7-PH8B-R23S-3WLV&Tip=0&Email=&TxId="

**Comment by jaredegan** [comment]
Thanks for reporting this. We already have this filed, and are looking to include the fix in our 2.4 releases, which should be out before the end of the month.

**Comment by jaredegan** [comment]
This will be fixed in the 2.4 versions of the iPad & iPhone apps. Also mind that the casing of "Unknown" (along with all the values) has changed to be all caps: "UNKNOWN".

**Comment by jaredegan** [comment]
2.4 has been released. Please reopen if this is still happening.
