### ISSUE TITLE
Return the total amount paid

### ISSUE THREAD

**Issue by dacology** [paypal/here-sideloader-api-samples#22]
At the moment the response does not return the amount paid. We send an invoice with a total value of say $123, it is possible that within PayPal Here we take a partial payment of $100. The sideloaded app is not aware of this discrepancy, is it possible to add this to the response? Or am I missing something?

&TotalPaid={TotalPaid}

**Comment by jaredegan** [comment]
It seems that you may have discovered a bug. Can we get some more information? Are you using iOS, Android or Windows? What version of the app? Can you break down the workflow that happens in this case? My assumption is:

- Your app opens PPH with an order of $125
- The user edits the order by removing some items or rebuilding the cart, making the order total $100
- The user completes the order
- {TotalPaid} ends up sending $125, but $100 is expected.

**Comment by dacology** [comment]
Yes this usecase is correct, except that {TotalPaid} is not returned. The request is: can we add total paid to the response to provide visibility of the final amount?

- I am testing on android and iOS.
- I not rebuild the order, but just pay a lesser amount.

**Comment by jaredegan** [comment]
Ah, I understand the ask now. I'm adding this to the backlog and will get back to this thread once it's in a pending version. Unfortunately it will likely be over a month before we can get this change live.

**Comment by jcorning99** [comment]
Would it also be possible to add a way to return the Net Paid Amount, i.e., the total amount paid less the PayPal fee?   Or to return the PayPal fee as a separate value?  if so, how soon could this be implemented?

**Comment by jaredegan** [comment]
I'd added this functionality, it will go live with PayPal Here version 2.5, which is targeted for early August release.

I've updated the docs: https://github.com/paypal/here-sideloader-api-samples/blob/master/docs/README.md

The text to use that will get replaced is `{GrandTotal}`

I'll ping this thread and close the issue once the release is out.

@jcorning99 The PayPal fee is actually not exposed to the clients by our the APIs we use with PayPal Here, so we currently can't return that value.

**Comment by dacology** [comment]
Great... Thanks

**Comment by rdantonio** [comment]
Will this work in Android as well? It seems to work well in iOS as of 2.5, but does not work in Android 2.5.1 (unless I'm doing something wrong).

Thanks!

**Comment by jcorning99** [comment]
I haven’t gotten it to work correctly in Android yet.  

 

With Android on a Samsung Galaxy S5 I was able to transfer control to PayPal Here.  It picked up all of the invoice information correctly and processed a credit card payment, but it would not transfer control back to my return URL.

 

Is that the same behavior that you’ve seen?

 

Regards,

 

 

John

**Comment by rdantonio** [comment]
John,

I don't think so. I am running into a few other issues with the 2.5.1 release of Android, but it does transfer control back to my application after processing is done. The filled-in returnUrl just doesn't have the GrandTotal argument like the iOS one has (it's also missing a few other fields like Tip and Email, but I think this might be because they are empty anyway?).

**Comment by jaredegan** [comment]
Looking into it, will get back to you

**Comment by lernerb** [comment]
@rdantonio @dacology Can you give me an example URL that you are sending?

This seems most likely an issue with the `v1` vs `v2` android API -> https://github.com/paypal/here-sideloader-api-samples/pull/20

**Comment by lernerb** [comment]
Also @rdantonio, what `other issues` are you running into with the 2.5.1 release of Android? Can take a look into them.

**Comment by rdantonio** [comment]
@lernerb Here's what I'm using for return URL in my Android application:

String returnURL = URLEncoder.encode("testscheme://paymentResult?Type={Type}&InvoiceId={InvoiceId}&Tip={Tip}&Email={Email}&TxId={TxId}&Number={Number}&GrandTotal={GrandTotal}", "UTF-8");

Based on the v2 API should I be doing "testscheme://paymentResult/v2?Type={Type}&InvoiceId={InvoiceId}&Tip={Tip}&Email={Email}&TxId={TxId}&Number={Number}&GrandTotal={GrandTotal}" ?

**Comment by lernerb** [comment]
@rdantonio I've made the change to support `{GrandTotal} on the Android PPH side.

I'll keep you informed when this build goes out and will update this thread, and will also update the README to reflect the version {GrandTotal} is added in Android vs. iOS.

**Comment by rdantonio** [comment]
This now appears to be working on Android as of the latest version. Thank you!

**Comment by lernerb** [comment]
Closing as {GrandTotal} is release on 2.5.1 of Android. Thanks.
