### ISSUE TITLE
Number not being returned in InvoiceId parameter, other issues

### ISSUE THREAD

**Issue by jcorning99** [paypal/here-sideloader-api-samples#25]
I've been experimenting with the WEB sample code, which I modified only slightly.  The relevant code is copied below.

According to the documentation, the value that I provide in the "number" field of the invoice is supposed to be returned as the "InvoiceId" parameter of the return URL.  But that is not the case.  When I complete the transaction, the return URL contains a PayPal-generated invoice number that looks like this:  INV2-6NHE-B5FV-FN7H-6EP3

I must have some way of passing a reference number back to my return page so I can link it to the original transaction.  What am I doing wrong?   Oddly enough, when I look at the transaction after logging on to www.PayPal.com, it does show the invoice number that I provided in the "number" field as the invoice ID.  Why isn't that value being provided in the return URL "InvoiceId" parameter?

ALSO:  When I test this on an iPad using Safari, when I complete the transaction and return to Safari, it opens up a new tab rather than returning me to the original tab.  Which means after completing ten transactions I would have ten tabs open, all pointing to the same page!  Is there any way to prevent this?

Here is my version of the onPay function:

	 <script>
  	   function onPay() {
    	   var itemsArr = [];
    	   var invoice = {};
    	   var myItems = {};
    	   var myItem = {};
           
    	   myItem['name'] = "OGO";
    	   myItem['description'] = "OGO plush toy";
    	   myItem['quantity'] = "1.0";
    	   myItem['unitPrice'] = "1.01";
    	   myItem['taxRate'] = '0.0';
    	   myItem['taxName'] = 'Tax';
    	   itemsArr.push(myItem);
    	   myItems['item'] = itemsArr;
      	 
      	 invoice['itemList'] = myItems;
      	 invoice['paymentTerms'] = 'DueOnReceipt';
      	 invoice['currencyCode'] = 'USD';
      	 invoice['number'] = '987601';
      	 invoice['discountPercent'] = '0';
      	 invoice['merchantEmail'] = 'jcorning@comcast.net';
      	 invoice['payerEmail'] = 'info@TroopWebHost.com';
          
      	 var returnUrl = 'http://www.troopwebhostcs.com/pph/index.htm';
      	 var retUrl = encodeURIComponent(returnUrl + "?Type={Type}&InvoiceId={InvoiceId}&Tip={Tip}&Email={Email}&TxId={TxId}&TotalPaid={TotalPaid}");
      	 var pphereUrl = "paypalhere://takePayment?returnUrl=" + retUrl;
      	 pphereUrl = pphereUrl + "&accepted=cash,card,paypal"
      	 pphereUrl = pphereUrl + "&step=choosePayment";
      	 pphereUrl = pphereUrl + '&invoice=' + escape(JSON.stringify(invoice));
      	 console.log(pphereUrl);
          
      	 return pphereUrl; 
      }
      
    	function pay() {	
      	window.location = onPay();
    	}
    </script>

**Comment by ppmtscory** [comment]
@jcorning99 I'm confirming something internally here with @jaredegan so that I'm clear before providing your answer.

As for your multiple tabs question, that would be something that you'd need to code on your end.  With my sample code I use, I just simply show a 'Success' or 'Failure' on the return URL with an 'OK' button.  Once that 'OK' button is clicked, I simply close that tab in the browser.

**Comment by jcorning99** [comment]
Is there any way to get it to specify a target window name when it returns to my site?  Like “target=PayPalClient”?  So that if a browser window is already open with that name, it would just re-use that window rather than opening a new one?

 

-jc

**Comment by ppmtscory** [comment]
@jcorning99 I'm not aware of a way to do that, no.

**Comment by jaredegan** [comment]
@jcorning99 Sorry for the late response. I've checked this out and reproduced your situation, thanks for the detailed notes. The documentation is a little vague, and I can understand the confusion. The value in number actually does get passed back to you, but it's in the `Number` parameter. If you switch to that value you'll be able to accomplish what you need to. I have clarified the documentation.

> Note: In the JSON input object (containing the invoice data), you may provide a unique invoice ID (in the `number` field). It must be unique to the merchant. If you leave out the number field, an invoice ID will be assigned, but if you provide the number field with a repeated value, or no value, (for example, if you send `“number”: “”`, or send `“number”: “12345”` every time), unexpected behavior will result. This value will be passed back to you in the return URL as `Number`.

https://github.com/paypal/here-sideloader-api-samples/blob/master/docs/README.md#structuring-the-returnurl-input-field

Regarding the multiple tabs, that behavior is out of our control. All we can do is tell iOS to open a URL, and it's up to the app intercepting that URL to decide what to do with it. In this case, the app that handles it is Safari, and Safari decides to open a new tab. Regarding your last idea with the `target=PayPalClient`, you should already be enabled to try something like that by adding it to the return URL, but again that behavior has to live in Safari.
