### ISSUE TITLE
(PLATFORM error 580022.) - Invalid request parameter: Payer Email cannot be blank

### ISSUE THREAD

**Issue by glaidler** [paypal/here-sideloader-api-samples#33]
We are getting the above intermittently with one of our customers.

Can you clarify what the validation rules are for payerEmail field - is it allowing empty strings but not null (the sample on Tim Messerschmit's blog has an emptry string), and considering the whole approach of paypal here, surely an email is not required?

https://devblog.paypal.com/paypal-here-sideloader-api/

**Comment by lernerb** [comment]
Hi Graham,

Can you give us the following information to help us debug the issue:

* Platform: `iOS` or `Android`?
* What version of the app is the user using?
* Do you have an example request that reproduces the error?

**Comment by lernerb** [comment]
If you look at our documentation [here] (https://github.com/paypal/here-sideloader-api-samples/blob/master/docs/README.md) we note the validation rule that you are looking for: 

> Sending an invoice field with no value (for example, sending “payerEmail”: “”) will cause unexpected behavior, so remove any fields that lack a value.

**Comment by glaidler** [comment]
Many thanks - sure that wasn't there before, but may well be wrong.

**Comment by glaidler** [comment]
All I would say is update the sample on the blog - this has a blank payerEmail.

**Comment by lernerb** [comment]
Will do, I've sent an email to Tim to update his blog.

**Comment by SeraphimSerapis** [comment]
Thanks @glaidler and @lernerb - I've updated the gist to reflect the payerEmail field changes.

**Comment by yogeshg1** [comment]
Hi,
@glaidler and @lernerb and @hkc3 
We are getting error please send me solution .
[error] => Array ( [0] => PayPal\Types\Common\ErrorData Object ( [errorId] => 580022 [domain] => PLATFORM [subdomain] => Application [severity] => Error [category] => Application [message] => Invalid request parameter: institutionId with value AP-6HK8380245497430W .

Thanks
