### ISSUE TITLE
Android: Number value constraints question

### ISSUE THREAD

**Issue by rdantonio** [paypal/here-sideloader-api-samples#34]
Quick question regarding the Number: what kind of constraints are set on this field besides avoiding duplicate numbers? I'm sending unique numbers every time similar to this: -2144680996 and the return url always returns {Number} instead of having a value. This worked fine previously (before 2.5.2) - has anything changed regarding this?

**Comment by lernerb** [comment]
All I'll need for this: are you using v1/ or v2/ of the api, and if so can you include the sideload url up until the {number} part?

**Comment by rdantonio** [comment]
Sure. I should be using v2:

paypalhere://takePayment/v2?accepted=cash,card&returnUrl=urlscheme://paymentResult?Type={Type}&InvoiceId={InvoiceId}&Tip={Tip}&Email={Email}&TxId={TxId}&Number={Number}&GrandTotal={GrandTotal}&invoice={"paymentTerms":"DueOnReceipt","currencyCode":"USD","number":"-2144680994","discountAmount":"0","itemList":{removed}}

Encoded version which is actually sent (with some stuff removed):
paypalhere://takePayment/v2?accepted=cash%2Ccard&returnUrl=urlscheme%3A%2F%2FpaymentResult%3FType%3D%7BType%7D%26InvoiceId%3D%7BInvoiceId%7D%26Tip%3D%7BTip%7D%26Email%3D%7BEmail%7D%26TxId%3D%7BTxId%7D%26Number%3D%7BNumber%7D%26GrandTotal%3D%7BGrandTotal%7D&invoice=%7B%22paymentTerms%22%3A%22DueOnReceipt%22%2C%22currencyCode%22%3A%22USD%22%2C%22number%22%3A%22-2144680994%22%2C%22discountAmount%22%3A%220%22%2C%22itemList%22%3A%7B -- removed -- %7D%7D

**Comment by rdantonio** [comment]
This is what I receive from PPH (I changed the InvoiceId but it is what I would expect). Could it have something to do with the Email also being blank?

urlscheme://paymentResult?Type=CASH&InvoiceId=PAYPALGENERATEDINVOICE&Tip=0&Email={Email}&TxId=&Number={Number}&GrandTotal=0.98

**Comment by lernerb** [comment]
Thanks, was able to reproduce. I've committed the fix for this and it should be going out in our next build. 

{Number} should now properly (again) get replaced using the v2 API. I'll keep this thread updated when I get the next release info.

**Comment by rdantonio** [comment]
Great, thank you very much!

**Comment by lernerb** [comment]
your welcome. :+1:

**Comment by lernerb** [comment]
@rdantonio we've released `Android Version 2.6.0` and it should be available to everyone on the GPS. Can you confirm the fix works for you?

**Comment by jaredegan** [comment]
Closing for housekeeping purposes, please reopen if you still have an issue.
