### ISSUE TITLE
Call back URL does not work on iOS 9

### ISSUE THREAD

**Issue by friedtofu** [paypal/here-sideloader-api-samples#36]
I think due to the security changes on iOS 9, Paypal Here app never seems to invoke the call back from my app. You can write a sample test using the here-sideloader-api-samples using any protocol to see whether this is true or not upon a successful transaction.

**Comment by jaredegan** [comment]
PayPal Here is not yet compiled with the iOS 9 SDK, so the new security changes should not affect it.

Did you have something working beforehand? If you share the URL you're using to open PayPal Here, we can provide some support.

**Comment by jaredegan** [comment]
Hi, no other users have mentioned any issue with iOS 9 & sideloader. Were you able to resolve this issue?
