### ISSUE TITLE
Sideloading only works on first load of Paypal Here app

### ISSUE THREAD

**Issue by atarsha** [paypal/here-sideloader-api-samples#55]
When I try to sideload the Paypal Here app, it works if the app isn't running, however if the app is already running it opens the app, but does not load the passed in invoice.

My workaround is killing Paypal Here after every transaction. This is clunky. Is this a bug?

@paypalsathya

**Comment by atarsha** [comment]
@paypalsathya is this API still supported? Can we get some assistance, or do we need to look for another solution?

**Comment by MggMuggins** [comment]
Do you need to go through the whole payment in order to get this behavior or will it also do that if you "Clear Sale"?

**Comment by atarsha** [comment]
@MggMuggins it doesn't seem to matter. If I open PPH, then open my app and press the button to sideload, no invoice. If I completely kill PPH and then open my app and press the button it works.

In other words, if PPH is already booted, regardless of state, the sideloading does not initiate a new invoice.

**Comment by MggMuggins** [comment]
That's strange, It works on my device. Are you sure your code is sound? This is mine (Assuming `pphUrl` is a valid Url):
```Java
Intent pphIntent = new Intent(Intent.ACTION_VIEW, Uri.parse(pphUrl));
PackageManager packageManager = context.getPackageManager();
ResolveInfo resolveInfo = packageManager.resolveActivity(pphIntent, PackageManager.MATCH_DEFAULT_ONLY);
if (resolveInfo == null) {
    AlertDialog.Builder pphNotFoundDialog = new AlertDialog.Builder(context);
    pphNotFoundDialog.setTitle("PayPal Here app Not Found!").setMessage("Install from Google Play");
    pphNotFoundDialog.show();
} else {
    context.startActivity(pphIntent);
}
```
This interface is just weird in general.

**Comment by atarsha** [comment]
@MggMuggins interesting. I wonder if this an iOS only issue.

Here is my code (React Native, so JavaScript feel:)

```
let items = {
            item: [
                {
                    name: "Basic Subscription Package",
                    description: "One year subscription (non-recurring) to my mobile app",
                    taxRate: "6.75",
                    unitPrice: "12.99",
                    taxName: "Tax",
                    quantity: 1
                }
            ]
        }

        let invoice = {
            paymentTerms: "DueOnReceipt",
            discountPercent: "0",
            currencyCode: "USD",
            number: "1235",
            payerEmail: "my@email.com",
            itemList: items
        }
        let returnUrl = 'utvtpos://paymentComplete/{result}Type={Type}&InvoiceId={InvoiceId}&Tip={Tip}&Email={Email}&TxId={TxId}'
        let acceptedPaymentTypes = 'cash,card,paypal'


        let PPHURL = "paypalhere://takePayment?accepted="
            + encodeURIComponent(acceptedPaymentTypes)
            + "&returnUrl="
            + encodeURIComponent(returnUrl)
            + "&invoice="
            + encodeURIComponent(JSON.stringify(invoice))
            + "&step=choosePayment"

        Linking.canOpenURL(PPHURL).then((supported) => {
            if (!supported) {
                window.alert('Must install the PayPal Here app')
            } else {
                return Linking.openURL(PPHURL)
            }
        }).catch(err => window.alert('An error occurred: ' + err.message))
```

Like I said, it works when PPH isn't already running so I would imagine that means my URL is correct.

**Comment by MggMuggins** [comment]
You could try Base64 encoding your JSON, I don't know how much good it would do, but maybe worth a shot.

**Comment by atarsha** [comment]
@MggMuggins I'll give that a whirl tonight and see if it makes any difference, then report back.

**Comment by MggMuggins** [comment]
Note that I passed a few flags to the base64 encoder so that it doesn't break up the output with newlines, makes it url safe, and remove padding at the end. You can see those (for android, :/) in #56

**Comment by atarsha** [comment]
I suspect this might be iOS only since it seems to be working for you. I tried Base64 as well, and verified against https://github.com/paypal/here-sideloader-api-samples/blob/master/docs/sample.html

Still behaves as described above.

**Comment by DJ92** [comment]
Hey @atarsha @MggMuggins, our latest release v3.2.3 is working as desired now. Feel free to raise any concerns you may have, if any.

**Comment by MggMuggins** [comment]
That's good to hear. I'll give it a few tries at some point and get back.
