### ISSUE TITLE
Base64 Encoding

### ISSUE THREAD

**Issue by MggMuggins** [paypal/here-sideloader-api-samples#56]
In general the documentation is not very clear on what needs to happen to any component of the url or how to base64 encode the URL. The Sample only illustrates Uri encoding, which is pretty straightforward. Are there any special flags that need to be passed to `android.util.Base64.encodeToString()` in order for this to work? Right now I'm using `Base64.URL_SAFE | Base64.NO_WRAP | Base64.NO_PADDING`.

**Comment by DJ92** [comment]
Hey @MggMuggins , We advise to use the `Base64.NO_WRAP` for this option.
