### ISSUE TITLE
Windows 10 - SurfaceBook Support..??

### ISSUE THREAD

**Issue by angelleye** [paypal/here-sideloader-api-samples#58]
The web-based sideloader does not trigger on a SurfaceBook running Windows 10..??

**Comment by ppmtscory** [comment]
We've recently decided to remove support for our Windows PPH App so will be closing this issue.  Please consider looking at our iOS and Android solutions.

**Comment by angelleye** [comment]
@ppmtscory Yeah, I noticed that while at an event.  Couldn't get logged in on my Surfacebook and was very confused.  I was actually trying to demo PayPal Here for somebody and it did not go well, obviously.

Was this announced somewhere?  Why are you killing Windows support?

**Comment by ppmtscory** [comment]
At this time, we're really just trying to double down our focus on platforms that are representative of our customers' choice currently.  Our main focus is iOS and Android at this time but we're working on a browser based SDK that would cater to the Windows folks as well.  More to come on that in Q1 sometime.
