### ISSUE TITLE
Auto-return to app after successful payment.

### ISSUE THREAD

**Issue by angelleye** [paypal/here-sideloader-api-samples#59]
Right now the only way to trigger anything after a payment is successful is on your return URL, but this is dependent on the user clicking the "New Sale" button in the Here app after the sale is complete.  If they don't push that button we can't trigger any post-payment processing calls, and our database does not update the order status properly.

Would be good to at least do an auto-return, or setup a trigger to a webhook..??

**Comment by glaidler** [comment]
+1

**Comment by DJ92** [comment]
Hey @angelleye @glaidler , we've duly noted webhooks as a feature on our roadmap. We'll keep you updated once we've prioritized those for our PPH SDK and App.
