### ISSUE TITLE
Explicit documentation of what a "Declined" return url will look like

### ISSUE THREAD

**Issue by glaidler** [paypal/here-sideloader-api-samples#60]
Hi, I am getting mixed information about what the sideloader return URL will look like when a card is declined.  Can you add this to the documentation and point me to it?

**Comment by DJ92** [comment]
We'll shortly update the documentation with the returnURL piece. Thanks

**Comment by glaidler** [comment]
Hi, any news on this; even just let me know as part of this issue; I am not reliably getting informed when a payment is declined and this is a big problem.

**Comment by DJ92** [comment]
Hi, This has been fixed for both Android and iOS Apps. It will be released in our upcoming PPH app releases.
