### ISSUE TITLE
3.0.81 (308108) breaks sideloader api

### ISSUE THREAD

**Issue by glaidler** [paypal/here-sideloader-api-samples#61]
Yet again, the latest release has broken the sideloader (js) api.  The symptom is that the amount isn't transferring.

This product needs some serious attention on it, as in it's current state not fit for purpose.

**Comment by DJ92** [comment]
Hey @glaidler, Sorry to hear about the problems being caused in the past few releases. The latest v3.2.3 release is working as desired. If there are any concerns, do let us know.
