### ISSUE TITLE
See Issue #63

### ISSUE THREAD

**Issue by dooms99** [paypal/here-sideloader-api-samples#64]
So in real world testing we have found that after doing a couple of transactions they begin to fail if done through the sideloader api but are successful if done directly. This has happened across numerous events for us now. Any suggestions to look at that would cause this type of behavior?

**Comment by ppmtscory** [comment]
You'll want to ensure that, if you're supplying your own invoice `number`, that it is unique for every single attempt and also that it doesn't exceed the 25 char limit.  If that's not the case, and you continue to see issues, please file a ticket with our support teams [here](https://www.paypal-support.com/).
